### ISSUE TITLE
 x86 JTAG hardware to play with ?

### ISSUE THREAD

**Issue by DarkoTominac** [Necrosys/x86-JTAG-Information#1]
Hi,
Is there any hardware available to play with x86 JTAG.
I have been trying to buy minnowboard - but no one is producing that one anymore
https://github.com/Necrosys/x86-JTAG-Information/blob/master/Connectors/XDP/XDP_P2.jpg

What HW are you using ?

**Comment by Necrosys** [comment]
Hello,
If you are individual, don't want to sign an NDA and want to play with an Intel XDP, your best option is to buy a used hardware.
Such as a reference board or a development board.
You can get many hints from the [coreboot](https://doc.coreboot.org/) repositories.
https://github.com/coreboot/coreboot/tree/master/src/mainboard/intel
https://github.com/coreboot/coreboot/commits/master/src/mainboard/intel
https://github.com/coreboot/fsp
https://github.com/coreboot/fsp/commits/master
With these hints, you should be able to ~~find~~hunt a used hardware which has an Intel XDP.
Usually, older one is easy to ~~find~~hunt.

I mainly use one of the Intel reference board.

If you have any further questions, please let me know.
Thanks,

**Comment by DarkoTominac** [comment]
Thanks!
I will try to find one as suggested.
